name: Public Beta

on:
  push:
    paths:
      - "src/**"
      - ".github/**"
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        java: [
            16
        ]
        os: [
            ubuntu-18.04,
            ubuntu-latest
        ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}

      - name: Get commit id
        id: getid
        run: |
          echo "::set-output name=commitID::${GITHUB_SHA::7}"
      - name: Display commit id
        run: |
          echo Carpet TCTC Addition commit-${{ steps.getid.outputs.commitID }} \(Public Beta\)
      - name: Set commit id in codes
        run: |
          sed -i "s/build.undefined/${{ steps.getid.outputs.commitID }}/g" gradle.properties
          sed -i "s/build.undefined/${{ steps.getid.outputs.commitID }}/g" src/main/java/top/catowncraft/CarpetTCTCAddition/Reference.java
          sed -i "s/Version Exception/Public Beta/g" src/main/java/top/catowncraft/CarpetTCTCAddition/Reference.java
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload assets to GitHub Action
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v2
        with:
          name: CarpetTCTCAddition-fabric-mc1.15-${{ steps.getid.outputs.commitID }}(Public Beta)
          path: build/libs/
