name: Public Beta
on:
  push:
    paths:
      - "src/**"
      - ".github/**"
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        java: [
          16-jdk,
          17-jdk
        ]
        os: [
          ubuntu-20.04
        ]
    runs-on: ${{ matrix.os }}
    container:
      image: openjdk:${{ matrix.java }}
      options: --user root
    steps:
      - name: Checkout the sources
        uses: actions/checkout@v2
      - name: Get commit id
        id: getid
        run: |
          echo "::set-output name=commitID::${GITHUB_SHA::7}"
      - name: Set commit id in codes
        run: |
          sed -i "s/build.undefined/${{ steps.getid.outputs.commitID }}/g" gradle.properties
          sed -i "s/build.undefined/${{ steps.getid.outputs.commitID }}/g" src/main/java/top/catowncraft/CarpetTCTCAddition/Reference.java
          sed -i "s/Version Exception/Public Beta/g" src/main/java/top/catowncraft/CarpetTCTCAddition/Reference.java
      - name: Read relevant fields from gradle.properties
        id: properties
        run: |
          path='./gradle.properties'
          for property in minecraft_version_out mod_version_detail mod_file_name
          do
            result=$(sed -n "/^[[:space:]]*$property[[:space:]]*=[[:space:]]*/s/^[[:space:]]*$property[[:space:]]*=[[:space:]]*//p" "$path")
            echo "$property: $result"
            echo ::set-output name=$property::"$result"
          done
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload assets to GitHub Action
        if: ${{ matrix.java == '16' }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.properties.outputs.mod_file_name }}-mc${{ steps.properties.outputs.minecraft_version_out }}-${{ steps.properties.outputs.mod_version_detail }}(Public Beta)
          path: build/libs/